# Uncomment the next line to define a global platform for your project
platform :ios, '17.3'

workspace 'ui_framework'
target 'ui_framework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'CocoaAsyncSocket'
    pod 'CocoaMQTT'
    pod 'AnyCodable'


end
